language: php

env:
    - SYMFONY_VERSION=2.3
    - SYMFONY_VERSION=2.4

before_script:
    - sed -i "s/>=2.3,<2.5-dev/~${SYMFONY_VERSION}.0/g" composer.json
    - sh -c "if [ '${TRAVIS_PHP_VERSION:0:3}' = '5.3' ]; then sed -i 's~</whitelist>~<exclude><file>src/SilexRouting/Application/RoutingTrait.php</file></exclude></whitelist>~g' phpunit.xml.dist; fi"
    - composer install

script:
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
    - php vendor/bin/coveralls -v

php:
    - 5.3
    - 5.4
    - 5.5
    - hhvm
