sudo: false
cache:
    directories:
        - $HOME/.composer/cache/files
language: php
php:
    - 5.5
    - 5.6
    - 7
    - hhvm
before_install:
    - composer require satooshi/php-coveralls --no-update
    - sh -c "if [ '$SYMFONY_DEPS_VERSION' = '3.0' ]; then sed -i 's/~2.8|3.0.*/3.0.*@dev/g' composer.json; fi"
    - sh -c "if [ '$SYMFONY_DEPS_VERSION' = '3.1' ]; then sed -i 's/~2.8|3.0.*/3.1.*@dev/g' composer.json; fi"
    - sh -c "if [ '$SYMFONY_DEPS_VERSION' = '' ]; then sed -i 's/~2.8|3.0.*/2.8.*@dev/g' composer.json; fi"
install:
    - composer install
script:
    - phpunit --coverage-clover build/logs/clover.xml
after_success:
    - sh -c "if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi"
matrix:
    include:
        - php: 7
          env: SYMFONY_DEPS_VERSION=3.0
        - php: 7
          env: SYMFONY_DEPS_VERSION=3.1
