sudo: false
cache:
    directories:
        - $HOME/.composer/cache
language: php
php:
    - 5.5
    - 5.6
    - 7
    - hhvm
before_install:
    - composer require satooshi/php-coveralls --no-update
    - sh -c "sed -i 's|silex\":\ \"~1.0|silex\":\ \"1.3.*@dev|g' composer.json"
    - sh -c "if [ '$SYMFONY_DEPS_VERSION' = '2.7' ]; then sed -i 's/~2\.3|3\.\*/2.7.*@dev/g' composer.json; fi"
    - sh -c "if [ '$SYMFONY_DEPS_VERSION' = '' ]; then sed -i 's/~2\.3|3\.\*/3.0.*@dev/g' composer.json; fi"
    - sh -c "if [ '$SYMFONY_DEPS_VERSION' = '2.8' ]; then sed -i 's/~2\.3|3\.\*/2.8.*@dev/g' composer.json; fi"
    - sh -c "if [ '$SYMFONY_DEPS_VERSION' = '2.3' ]; then sed -i 's/~2\.3|3\.\*/2.3.*@dev/g' composer.json; fi"
install:
    - composer install
before_script:
    - sh -c "if [ '${TRAVIS_PHP_VERSION:0:3}' = '5.3' ]; then sed -i 's~</whitelist>~<exclude><file>src/SilexRouting/Application/RoutingTrait.php</file></exclude></whitelist>~g' phpunit.xml.dist; fi"
script:
    - phpunit --coverage-clover build/logs/clover.xml
after_success:
    - sh -c "if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi"
matrix:
    include:
        - php: 7
          env: SYMFONY_DEPS_VERSION=2.3
        - php: 7
          env: SYMFONY_DEPS_VERSION=2.7
        - php: 7
          env: SYMFONY_DEPS_VERSION=2.8
