language: php

env:
    - SYMFONY_DEPS_VERSION=2.3
    - SYMFONY_DEPS_VERSION=2.4

before_script:
    # symfony/*
    - composer self-update
    - sh -c "if [ '$SYMFONY_DEPS_VERSION' = '2.4' ]; then sed -i 's/>=2.3,<2.5-dev/2.4.*@dev/g' composer.json; composer update --dev --prefer-source; fi"
    - sh -c "if [ '$SYMFONY_DEPS_VERSION' = '2.3' ]; then sed -i 's/>=2.3,<2.5-dev/2.3.*@dev/g' composer.json; composer update --dev --prefer-source; fi"

script: vendor/bin/phpunit

php:
  - 5.3
  - 5.4
  - 5.5

